### ISSUE TITLE
YTDownloader Portable

### ISSUE THREAD

**Issue by candrapersada** [gek64/MotrixPortable#2]
can you make YTDownloader portable?
link https://github.com/aandrew-me/ytDownloader
## Used technologies
- [yt-dlp](https://github.com/yt-dlp/yt-dlp)
- [Electron](https://www.electronjs.org/)
- [ffmpeg](https://ffmpeg.org/)
- [nodeJS](https://nodejs.org/en/)

**Comment by gek64** [comment]
done!
https://github.com/gek64/build-apps-scripts/raw/main/portable/YTDownloaderPortable.zip
use 7zip to extract files from `YTDownloader_Win.exe/$PLUGINSDIR/app-64.7z`
then put all files to `YTDownloaderPortable\App\YTDownloader\`
run `YTDownloaderPortable\ytDownloaderPortable.exe`
